version: '3.9'

services:
  dbpatient:
    container_name: dbpatient
    build: ../mediscreen/database
    environment:
      MYSQL_DATABASE: bdd_mediscreen
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "13306:3306"
    restart: always

  mongodb:
    container_name: mongodb
    build: ../mediscreen_mdb/database
    ports:
      - "2727:27017"
    restart: always

  patient:
    container_name: patient
    build: ../mediscreen
    environment:
      spring.datasource.username: "root"
      spring.datasource.password: "rootroot"
      spring.datasource.url: "jdbc:mysql://dbpatient:3306/bdd_mediscreen"
    ports:
      - "8081:8081"
    depends_on:
      - dbpatient
    restart: always

  patientnotes:
    container_name: patientnotes
    build: ../mediscreen_mdb
    environment:
      spring.data.mongodb.uri: "mongodb://mongodb:27017/MediscreenDatabase"
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    restart: always

  patientassess:
    container_name: patientassess
    build: ../mediscreen_assess
    environment:
      mediscreen.url: "http://patient:8081"
      mediscreen-mdb.url: "http://patientnotes:8082"
    ports:
      - "8080:8080"
    depends_on:
      - patient
      - patientnotes
    restart: always



