version: '3.9'

services:
  mongodb:
    container_name: mongodb
    build: ../mediscreen_mdb/database
    ports:
      - "2717:27017"

  patient_mdb:
    container_name: patient_mdb
    build: ../mediscreen_mdb
    ports:
      - "882:8082"
    depends_on:
      - mongodb
    environment:
      spring.datasource.url: "mongodb://mongodb:27017/MediscreenDatabase"