version: '3.9'

services:
  db_mysql:
    container_name: db_mysql
    build: ../mediscreen/database
    ports:
      - "13306:3306"

  patient:
    container_name: patient
    build: ../mediscreen
    ports:
      - "881:8081"
    depends_on:
      - db_mysql
    environment:
      spring.datasource.url: "jdbc:mysql://db_mysql:3306/bdd_mediscreen"

  mongodb:
    container_name: mongodb
    build: ../mediscreen_mdb/database
    ports:
      - "2727:27017"

  patient_notes:
    container_name: patient_notes
    build: ../mediscreen_mdb
    ports:
      - "882:8082"
    depends_on:
      - mongodb
    environment:
      spring.data.mongodb.uri: "mongodb://mongodb:27017/MediscreenDatabase"

  patient_assess:
    container_name: patient_assess
    build: ../mediscreen_assess
    ports:
      - "880:8080"
    depends_on:
      - patient
      - patient_notes
    environment:
      clients.patient: "http://patient:8081"
      clients.patient_notes: "http://patient_notes:8082"

  patient_ui:
    container_name: patient_ui
    build: ../mediscreen_ui
    ports:
      - "890:8090"
    depends_on:
      - patient
      - patient_notes
      - patient_assess
    environment:
      clients.patient: "http://patient:8081"
      clients.patient_notes: "http://patient_notes:8082"
      clients.patient_assess: "http://patient_assess:8090"
